export type Lender={name:string;type:string;products:string[];states:string;contact:string;email:string;phone:string;web:string;linkedin:string;source:string};
const li=(name:string)=>`https://www.linkedin.com/search/results/companies/?keywords=${encodeURIComponent(name)}`;
const rows:[string,string,string,string,string,string,string,string,string?][]=[
['ABL Funding','Direct private lender','Bridge|Construction|Fix & Flip|Refinance','Nationwide; Texas and PNW contacts','Chris Burdick / Jarrod Covey','Chris.Burdick@ablfunding.com','503-997-9908','https://ablfunding.com'],
['A10 Capital','Institutional CRE lender','Bridge|Commercial|Multifamily','Nationwide','Tyler Jackson','tjackson@a10capital.com','208-577-5044','https://a10capital.com'],
['Acra Lending','Non-QM / DSCR lender','DSCR|Refinance|Rental','Nationwide; includes Oregon','Matt Schwartz','Matthew.Schwartz@AcraLending.com','949-669-5856','https://acralending.com'],
['ALMI Lending','Direct private lender','Fix & Flip|DSCR|Bridge|Construction','Nationwide','','','','https://almilend.com'],
['Alto Capital','Private lender','Fix & Flip|Bridge|Construction|DSCR|Multifamily','Nationwide','','info@altocapital.com','305-381-0153',''],
['American Life Financial','Insurance / permanent capital','Commercial|Multifamily|Industrial|Medical Office','Nationwide','Scott Emrich','scott@americanlifefinancial.com','480-420-2538',''],
['Angel Oak Mortgage Solutions','Non-QM / DSCR lender','DSCR|Refinance|Rental','Nationwide; includes Oregon','Kevin McAllister','Kevin.McAllister@angeloakms.com','971-295-6935','https://angeloakms.com'],
['Anchor Loans','Direct private lender','AD&C / Land Development|Construction|Fix & Flip|Bridge','48 states; active Texas','','','','https://www.anchorloans.com'],
['Atlas CRE Capital','CRE capital advisor / lender','Multifamily|Construction|Land|Office|Retail','Nationwide','Andrew Speer','andrew@atlasCREcapital.com','521-921-4620',''],
['AVANA Capital','Direct commercial lender','SBA 504|Construction|Bridge|Commercial','Nationwide','Sanat Patel','Sanat.Patel@AvanaCompanies.com','213-700-7775','https://avanacapital.com'],
['Balcones Commercial Capital','Private lender / arranger','Bridge|Rehab|Construction','Texas','Brent Brentham','brent@balconescommercialcapital.com','254-760-7560','https://balconescommercialcapital.com'],
['Bayport Funding','Direct portfolio lender','Ground-Up|Bridge|Multifamily|Rehab','Nationwide','Originations','info@bayportfunding.com','800-609-7707','https://bayportfunding.com'],
['BD Lending','Direct private lender','Refinance|Rehab|Bridge','Texas and select markets','Deal Desk','','','https://www.bdlend.com'],
['Berkadia','Institutional mortgage banking','Multifamily|Hospitality|Land|Build-to-Rent|Healthcare','Nationwide','Jack Alvarez','jack.alvarez@berkadia.com','949-322-7797','https://berkadia.com'],
['Bloomfield Capital','Private debt fund','Bridge|Preferred Equity|Multifamily|Commercial','Nationwide','Brent','brent@bloomfieldcapital.com','','https://bloomfieldcapital.com'],
['Boardwalk Funding','Direct private lender','Fix & Flip|Bridge|Rental','Texas','Loan Desk','loans@hardmoneytx.com','512-699-3649','https://www.boardwalkfunding.com'],
['Boston Trust Corp.','Hard money lender','Fix & Flip|Bridge|Land|Construction','Nationwide; confirm state','Chris Anderson','','617-752-7000',''],
['BRC Loans','Direct private lender','Residential|Multifamily|Commercial|Bridge','Nationwide; confirm state','David Takakawa','david@brloans.com','213-248-5657',''],
['Builders Capital','Institutional construction lender','AD&C / Land Development|Construction|Build-to-Rent|Bridge','Nationwide; Washington HQ','Originations','info@builderscapital.com','888-540-9009','https://www.builderscapital.com'],
['Builders Land Capital','Direct private land lender','Land|Land Banking|AD&C / Land Development','Nationwide; confirm county','Submissions','','','https://builderslandcapital.com'],
['Built Lending','Direct private lender','Construction|Fix & Flip|Bridge|DSCR','ID, TX, CO, TN, OH, NC, SC, GA, FL','','','','https://built-lending.com'],
['Capital Funding Financial','Private lender','Hard Money|Fix & Flip|DSCR|Construction|Commercial Bridge','Nationwide','','','866-999-2011','https://capitalfundingfinancial.com'],
['Casa Lending','Hard money lender','Fix & Flip|Construction|DSCR|Portfolio','Nationwide; confirm state','Jamie Pmascaro','jamiepmascaro@gmail.com','888-433-2272',''],
['Ceasons Holdings','Direct private lender','Refinance|Bridge','Texas','John','john@ceasonsholdings.com','469-233-0450','https://ceasonsholdings.com'],
['Cetan Funds','Direct regional capital','Land|Construction|AD&C / Land Development','Oregon and Washington','Zach Smith','','458-215-3200','https://cetanfunds.com'],
['City Bay Capital','Private CRE lender','Multifamily|Hospitality|Bridge','Nationwide with state exclusions','','info@citybaycapital.com','212-691-2695',''],
['Conventus','Direct private lender','Fix & Flip|DSCR|Bridge|Construction','44 states','','','','https://cvlending.com','https://www.linkedin.com/company/cvlending'],
['CoreVest','Institutional investor lender','DSCR|Bridge|Construction|Multifamily','Nationwide','','info@cvest.com','844-223-2231','https://www.corevestfinance.com'],
['Corridor Funding','Private lender','Fix & Flip|Construction|DSCR','Nationwide; confirm state','Grayson Wester','grayson@corridorfunding.com','830-358-3995',''],
['CV3 Financial','Institutional private lender','Construction|Bridge|DSCR|Fix & Flip','47 states','Todd Kaplan','todd.kaplan@cv3financial.com','818-521-9922','https://www.cv3financial.com'],
['DLP Lending','Private credit platform','Bridge|DSCR|Multifamily','Nationwide','Ross Billington','ross.billington@dlpcapital.com','904-417-7528','https://dlpcapital.com'],
['Easy Street Capital','Private lender','Construction|DSCR|Fix & Flip','Nationwide; includes WA and OR','','','866-828-0062','https://easystreetcap.com'],
['Equity Cap Lending','Debt and equity provider','Bridge|DSCR|Fix & Flip|Construction','Nationwide','Sam Carella','SAM@EquityCapLending.com','407-552-5483',''],
['Eqcho Capital','Capital advisor / lender','Bridge|Commercial|All Asset Classes','Nationwide','Robert Kerr','info@eqcho.com','360-637-6781','https://eqcho.com'],
['Eyzenberg & Company','Capital advisor','C-PACE|Senior Debt|Mezzanine|Preferred Equity|JV Equity','Nationwide','Stephen Kass','skass@eyzenberg.com','305-995-0777','https://eyzenberg.com'],
['First Equity Funding','Wholesale private lender','DSCR|Fix & Flip','Nationwide; confirm state','Frank Luposki','flopuski@fefunding.com','732-820-9975','https://fefunding.com'],
['Forbix Capital Corp.','Private CRE lender','Mezzanine|Preferred Equity|Multifamily|Commercial','Nationwide','Valerie Harpner','valerie.hapner@forbix.com','818-325-5880','https://forbix.com'],
['FundLoans Capital','Non-QM / DSCR lender','DSCR|No-Ratio|Refinance','Nationwide; includes Oregon','Shane Colson','scolson@fundloans.com','520-271-1810','https://www.fundloans.com'],
['Gelt Financial','Private lender','Bridge|Hard Money|Residential|Commercial','Nationwide; confirm state','Marci Berger','MBerger@Geltfinancial.com','561-221-0900','https://geltfinancial.com'],
['Genesis Capital','Institutional private lender','Construction|Fix & Flip|Bridge|DSCR','Nationwide','Dominic Lingua','dominic.lingua@genesiscapital.com','818-373-9735','https://genesiscapital.com'],
['Gold Quest Group','Hard money lender','Refinance|Rehab|Bridge','Texas','Loan Specialist','Info@GoldQuestGroup.com','713-621-6458','https://www.goldquestgroup.com'],
['Green Lake Fund','Private commercial lender','Multifamily|Mixed-Use|Retail|Hospitality|Special Use','Nationwide; larger transactions','','deals@greenlakefund.com','626-460-1628','https://greenlakefund.com'],
['Greystone','Institutional CRE lender','Multifamily|Affordable Housing|Senior Housing|Healthcare','Nationwide','','','','https://greystone.com'],
['Hall Structured Finance','Direct private CRE lender','Construction|Bridge|Multifamily|Hospitality','Nationwide','Bryce Yamauchi','byamauchi@hallstructured.com','214-686-9230','https://hallstructuredfinance.com'],
['Hearthstone Residential Holdings','Institutional residential equity','Land Banking|JV Equity|Homebuilder Finance','Select U.S. markets','Investment Team','','','https://www.hearthstone.com'],
['HouseMax Funding','Private lender','Fix & Flip|Construction|DSCR|Refinance','Nationwide; confirm state','Eric Thomas','ethomas@housemaxusa.com','512-413-1707','https://housemaxfunding.com'],
['ICE Capital Group','Private lender','Fix & Flip|Bridge|Rehab|Construction|Multifamily','Nationwide','Jeremiah Sullivan','JSullivan@icecapgroup.com','312-262-3200','https://icecapgroup.com'],
['INCA Capital','Direct private lender','Commercial|Residential|Land|Construction|Development','Western U.S.','Brandon Walters','brandon@incacapital.com','480-947-5900 x14','https://incacapital.com'],
['Ladder Capital','Institutional CRE lender / REIT','Bridge|Fixed Rate|Commercial|Multifamily|Hospitality','Nationwide','','contact@laddercapital.com','212-715-3170','https://www.laddercapital.com'],
['LendBridge Capital','Family-office backed direct lender','Commercial Bridge|Construction|Refinance|Partner Buyout','Nationwide','Originations','','','https://www.lendbridgecapital.com','https://www.linkedin.com/company/lendbridgecapital'],
['LendingOne','Institutional private lender','DSCR|Fix & Flip|Construction|Build-to-Rent','Nationwide','','','866-850-5368','https://lendingone.com'],
['LFB Ventures','Debt and equity advisor','AD&C / Land Development|Lot Banking|Construction|Bridge','Nationwide','John Friedrich','john@lfbventures.com','858-926-6640','https://lfbventures.com'],
['Lighthouse Lending','Private lender','Bridge|Fix & Flip|Construction','Texas','Alfonso Barrera-Villarreal','Alfonso@LighthouseLoan.com','469-813-7363','https://www.lighthouseloan.com'],
['Lima One Capital','Institutional private lender','Multifamily|Bridge|Rehab|Construction|DSCR','Nationwide','Tara Scott','tscott@limaone.com','208-901-5443','https://www.limaone.com'],
['LIONSCOVE','Private debt fund / direct lender','AD&C / Land Development|Construction|Bridge','WA, OR, ID, CA','Builder Relations','builders@lionscove.com','855-438-7051','https://lionscove.com'],
['Livi Kapital','Private equity / preferred equity','Preferred Equity|Build-to-Suit|Multifamily','Nationwide; confirm market','Jonathan Livi','jl@livikapital.com','516-604-3636',''],
['Marquee Funding Group','Private lender','Bridge|Construction Completion|Commercial','Nationwide','Eric Baehr','EBaehr@marqueefg.com','','https://www.marqueefundinggroup.com'],
['Marketplace Realty Advisors','Private lender / advisor','Bridge|Land Development|Construction','Pacific Northwest','Private Lending Team','','','https://www.marketplacerealtyadvisors.com'],
['Matador Lending','Hard money lender','Refinance|Fix & Flip|Bridge','Texas','Loan Desk','hello@matadorlending.com','713-366-4668','https://www.matadorlending.com'],
['Monroe Capital','Institutional private credit','Direct Lending|Structured Credit|Real Estate|Equity','U.S. and Canada','Jason Starr','jstarr@monroecap.com','646-386-2423','https://monroecap.com'],
['Northmarq','Mortgage banking / capital markets','Permanent Debt|Equity|Multifamily|Commercial','Nationwide','Thomas Ware','tware@northmarq.com','813-223-1653','https://www.northmarq.com'],
['Offset Capital','Capital advisor','Senior Bridge|Mezzanine|Preferred Equity','Nationwide','Ray','info@offsetcap.com','516-202-4001',''],
['Pacific Northwest Capital Partners','Private hard-money lender','Land|Development|Construction|Multifamily','Washington','Loan Team','','','https://bestwashingtonlender.com'],
['Parkview Financial','Alternative investment manager / lender','Bridge|Construction|Multifamily|Commercial','Major U.S. markets','Originations','','','https://www.parkviewfinancial.com','https://www.linkedin.com/company/parkviewloan'],
['PGIM Real Estate Finance','Institutional lender / insurer affiliate','Commercial|Multifamily|Agriculture|Structured Debt','Global','','','','https://www.pgim.com/real-estate'],
['QuickLend Capital','Direct private lender','DSCR|Fix & Flip|Construction|Bridge','Nationwide with state exclusions','','','201-335-8951','https://www.quicklendcapital.com','https://www.linkedin.com/company/quicklend-capital'],
['Rain City Capital','Private lender','Construction|DSCR|Fix & Flip|Bridge','24+ states; includes WA and OR','Chris Burdick','chrisb@raincitycapital.com','503-997-9908','https://www.raincitycapital.com'],
['Reef Capital Partners','Private credit / private equity','Private Credit|Private Equity|Opportunistic Real Estate','Nationwide','Andi Johnson','Andi@reefcp.com','801-427-5045','https://reefcp.com'],
['Rehab Financial Group','Private lender','Fix & Flip|Construction|Multifamily|DSCR','18 states; confirm state','Chris Vena','cvena@rehabfinancial.com','610-645-9939 x318','https://rehabfinancial.com'],
['ReProp Financial','Private lender','Bridge|Agricultural|Long-Term Finance','Western U.S.; confirm state','','info@reprop.net','707-444-7741','https://repropfinancial.com'],
['Rhine Legacy Capital','Balance-sheet CRE lender','Senior Bridge|Multifamily|Industrial|Retail','Nationwide','Originations','','','', 'https://www.linkedin.com/company/rhine-legacy-capital'],
['Ridge Street Capital','Private lender','Fix & Flip|DSCR|Construction|Short-Term Rental','35 states','','','','https://ridgestreetcap.com','https://www.linkedin.com/company/ridge-street-capital'],
['Rok Lending','Private CRE lender','Bridge|Condominium|Hospitality|Development','Nationwide; confirm state','','info@roklending.com','305-680-1192',''],
['Sachem Capital Corp.','Publicly traded hard-money lender','Bridge|Commercial|Short-Term','Nationwide; confirm state','','JGB@SACHEMCAPITALCORP.com','203-208-4560','https://sachemcapitalcorp.com'],
['Seattle Funding Group','Direct private lender','Commercial|Construction|Bridge|Residential','Washington / PNW','','','425-455-1733','https://www.seattlefundinggroup.com'],
['Silver Hill Funding','Commercial lender','Multifamily|Mixed-Use|Retail|Industrial|Self Storage','Nationwide; confirm state','Felipe Herrera','FHerrera@Silverhillfunding.com','786-648-7579','https://silverhillfunding.com'],
['SimpleCREDIT','Direct private lender','Residential Bridge|Construction|Rehab','Nationwide','Originations','','','https://www.simpleciti.com/SC/','https://www.linkedin.com/company/simplecredit'],
['SIMS Mortgage Funding','Institutional mortgage banking','Healthcare|Senior Housing|Hospital|Multifamily Construction','Nationwide','Anthony Luzzi','aluzzi@hjsims.com','201-307-9383','https://hjsims.com'],
['Socotra Capital','Hard money lender','Commercial Bridge|Fix & Flip|Construction|Cash-Out Refi','Western U.S.; confirm state','','','855-889-7626','https://socotracapital.com'],
['Soviero Capital','Asset-based private lender','Hard Money|Commercial|Residential','Florida','Loan Desk','info@sovierocapital.com','561-278-0098','https://sovierocapital.com'],
['Spreo Capital','Private lender','Bridge|Renovation|Construction|Fix & Flip|DSCR','Nationwide; confirm state','William LaRouche','wlarouche@spreocapital.com','310-283-6288',''],
['Streit Lending','Family-office balance-sheet lender','Bridge|Construction|Commercial|Cannabis','Western, Midwest and Southern U.S.','Auriel Streit','','','https://www.streitlending.com','https://www.linkedin.com/company/streit-lending'],
['Stronghill Capital','Permanent investment-property lender','Commercial|Multifamily|DSCR','Nationwide; confirm state','Brian Simmons','','425-308-1532','https://stronghill.com'],
['Sundance Bay','Private real estate credit / equity','Structured Debt|Equity|Multifamily|Net Lease','Nationwide','Lance Frame','loans@sundancebay.com','818-726-7473','https://sundancebay.com'],
['Texas Equity Lending','Direct private lender','Refinance|Rehab|Bridge','Texas','Chris','chris@texasequitylending.com','800-333-8323','https://www.texas-hardmoney.com'],
['Texas Land Lenders','Private-lender arranger','Land|AD&C / Land Development','Texas and nationwide','Submissions','','','https://www.texaslandlenders.com'],
['TLOA Capital','Private lender / arranger','Construction|Bridge|Special Purpose','Eastern U.S. primarily','Chris Shirley','chris@tloacapital.com','',''],
['Tower Fund Capital','Private lender','Multifamily|Mixed-Use|Bridge|Fix & Flip|Refinance','Nationwide; confirm state','Jesse Chafitz','jesse@towerfundcapital.com','516-434-8232',''],
['Trez Capital','Private real estate debt fund','Construction|Multifamily|Land Development|Bridge','U.S. and Canada','U.S. Originations','sales@trezcapital.com','877-689-0821','https://www.trezcapital.com'],
['Trueline Capital','Private lender','Construction|Fix & Flip|Bridge|Commercial','Washington and Oregon','Chris Maskill','chrism@truelinecapital.com','206-702-2731','https://truelinecapital.com'],
['Velocity Mortgage Capital','Investor mortgage lender','DSCR|Multifamily|Mixed-Use|Commercial','Nationwide; confirm state','','generatevelocitysupport@velocitymortgage.com','888-822-3304','https://www.velocitymortgage.com'],
['Veristone Capital','Direct private lender','Land Development|Construction|Bridge','Washington / Pacific Northwest','Originations','','','https://loans.veristonecapital.com'],
['WADOT Capital','Direct private lender','Land Development|Construction|Commercial','WA, OR, ID','Submissions','','','https://wadot.com'],
['Woodlock Capital','Private lender / strategic capital','Multifamily|Land Development|Retail|JV','Nationwide; confirm market','Jeffrey Goodman','jeff@woodlockcapital.com','516-644-0104',''],
['Yorktown Capital','Private lender / marketplace','Land|Lot Development|Construction','Select major U.S. metros','Land Team','','','https://yorktowncapital.com']
,
['1Oak Lending','Family-office-backed direct lender','Commercial Bridge|Construction|Transitional CRE','Select U.S. markets; verify current coverage','Originations','','','https://1oaklending.com'],
['1892 Capital Partners','Family-office direct lender','Bridge|Construction|Land|Development|Fix & Flip','Washington, Utah and Hawaii; verify current coverage','Originations','','','https://1892capital.com'],
['ARC Family Office','Family office / direct lender','Bridge|Construction|Land|DSCR|Reverse 1031','47 states; excludes OR, AK and UT per published program','Direct Lending Team','','','https://www.arcfamilyoffice.com/direct-lending'],
['Backflip','Fintech / direct private lender','Fix & Flip|Rehab','Nationwide with state exclusions','Lending Team','','','https://dobackflip.com','https://www.linkedin.com/company/dobackflip'],
['Bridge Financing Group','Direct private lender','Bridge|Construction|Rehab|Refinance|1031 Exchange','Multiple states; primarily Eastern U.S.','Originations','','','https://www.bfgdirect.com'],
['CapitalConnect','Private lender','Fix & Flip|DSCR|Construction|Commercial Bridge','TX, CO, GA, TN and WA; verify current coverage','Blaise Brewer','','','', 'https://www.linkedin.com/company/capitalconnect-me'],
['Center Street Lending','Direct private lender','Bridge|Fix & Flip|Construction|DSCR|Short-Term Rental','Most U.S. states; verify exclusions','Originations','','','https://centerstreetlending.com'],
['Central Lending','Direct private lender','Bridge|Fix & Flip|Construction|DSCR','Most U.S. states; verify exclusions','Originations','','','https://centrallending.com'],
['Certain Lending','Direct private lender','Fix & Flip|Bridge|Construction|DSCR|Short-Term Rental','Nationwide with state exclusions','Originations','','','https://certainlending.com'],
['CR Lending','Direct hard-money lender','Bridge|Fix & Flip|Rehab-to-Rent|Construction|Cash-Out Refinance','Texas, Tennessee and Florida','Originations','','','https://crlending.com'],
['CRE Bridge Capital','Direct CRE lender','Commercial Bridge|Value-Add|Refinance','Nationwide; verify current state coverage','Joe Salzer','','','https://www.crebridgecapital.com','https://www.linkedin.com/company/crebridgecapital'],
['Crossroads Investment Lending','Direct private lender','Fix & Flip|Bridge|Construction|DSCR','Greater Kansas City region','Loan Team','','913-766-2900','https://crossroadsinvestmentlending.com','https://www.linkedin.com/company/crossroadsinvest'],
['Elevated Equities','Family office / direct CRE lender','Senior Debt|Construction|Development|Bridge|Refinance','Nationwide; verify current coverage','Originations','','','https://elevatedequities.com'],
['Fairbridge Asset Management','Private real estate debt fund','Bridge|Construction|Multifamily|Residential','Nationwide; verify current coverage','Originations','','','https://fairbridgeassetmanagement.com'],
['First Bridge Lending','Direct private lender','Residential Bridge|Commercial Bridge|Fix & Flip','California, Arizona, Oregon and Washington','Originations','','','https://firstbridgelending.com','https://www.linkedin.com/company/first-bridge-lending'],
['FlipCo Financial','Direct private lender','Fix & Flip|Bridge|Purchase|Refinance','AL, AR, FL, GA, IN, KS, KY, MO, NC, OH, OK, PA, SC, TN, TX and VA','Originations','','','https://flipcofinancial.com'],
['GW Private Capital','Private-money lender / arranger','Bridge|Fix & Flip|Construction|Commercial|Junior Lien','California','Aldo Baltodano','','','https://gwprivatecapital.com'],
['Lancewood Capital','Family office / principal lender','Commercial Bridge|Construction Completion|Lender Finance','Nationwide major markets','Originations','','','https://www.lancewoodcapital.com','https://www.linkedin.com/company/lancewood-capital'],
['Macoy Capital','Direct private lender','Bridge|DSCR|Ground-Up Construction|Multifamily|Land Development','Nationwide; verify state eligibility','Originations','info@macoycapital.com','','https://macoycapital.com'],
['Money Line Ventures','Private real estate lender','Fix & Flip|Construction|Bridge','North Carolina and South Carolina','Originations','','','https://moneylineventures.com'],
['Norfolk Capital','Private / hard-money lender','Fix & Flip|DSCR|Construction|Bridge|Rehab','Verify current lending states','Originations','','','https://norfolkcapital.com','https://www.linkedin.com/company/norfolk-capital'],
['Olyvian Capital Group','Family office / direct bridge lender','Bridge|Commercial|Multifamily|Mixed-Use','New York metropolitan area','Originations','','','https://olyviancapital.com'],
['Park Place Finance','Direct private lender','Fix & Flip|Bridge|DSCR|Construction','Nationwide; investment property only','Loan Desk','','866-409-3460','https://www.parkplacefinance.com','https://www.linkedin.com/company/park-place-finance-llc---mortgage-lender'],
['PrideCo Loans','Direct private lender','Bridge|Fix & Flip|Construction|DSCR|Cash-Out Refinance','Key U.S. investment markets; verify state eligibility','Gary Wallace','','','https://pridecoloans.com'],
['Quick Real Estate Funding','Private / hard-money lender','Fix & Flip|DSCR|Bridge|Construction','Nationwide; verify state eligibility','Leidy Robles','','','https://quickrealestatefunding.com','https://www.linkedin.com/company/quickrealestatefunding'],
['Residential Capital Partners','Private-money lender','Fix & Flip|Bridge|DSCR|Rental','Nationwide; verify state eligibility','Broker Team','','','https://residentialcapitalpartners.com'],
['Revere Capital','Direct balance-sheet lender / debt fund','Bridge|NNN Construction|Mezzanine|Commercial','Nationwide','Originations','','','https://www.reverecapital.com'],
['RWC Lending','Direct CRE lender','Stabilized CRE|Commercial Bridge|Multifamily','Nationwide','Ian Katz','','','https://www.rwclending.com','https://www.linkedin.com/company/rwc-lending'],
['SCRED','Private evergreen real estate credit fund','Senior Bridge|Junior Bridge|Commercial|Residential','Nationwide; verify current coverage','Originations','','','https://scred.us','https://www.linkedin.com/company/scred-us'],
['SLA Capital','Private lender','DSCR|Fix & Flip|Construction|Bridge','Nationwide; verify state exclusions','Originations','','','https://www.slacapital.com'],
['Stratton Equities','Direct private / non-QM lender','DSCR|Fix & Flip|Commercial Bridge|Rental|Multifamily','Nationwide','Loan Desk','','','https://www.strattonequities.com','https://www.linkedin.com/company/strattonequities'],
['TBG Capital','Direct lender / real estate debt fund','Bridge|Construction|Residential Development','WA, CO, UT, TX, NC and GA; verify current coverage','Originations','','','https://www.tbgcap.com'],
['Titan Capital','Direct private lender','Commercial Bridge|Construction|Land|Multifamily|Mixed-Use','Nationwide; verify current coverage','Originations','','','https://titancapital.com']
];
export const lenders:Lender[]=rows.map(r=>({name:r[0],type:r[1],products:r[2].split('|'),states:r[3],contact:r[4],email:r[5],phone:r[6],web:r[7],linkedin:r[8]||li(r[0]),source:r[0].match(/ALMI|Built Lending|Conventus|QuickLend|SimpleCREDIT|Parkview|Rhine|Ridge Street|Streit|LendBridge|1Oak|1892|ARC Family|Backflip|Bridge Financing|CapitalConnect|Center Street|Central Lending|Certain Lending|CR Lending|CRE Bridge|Crossroads|Elevated Equities|Fairbridge|First Bridge|FlipCo|GW Private|Lancewood|Macoy|Money Line|Norfolk|Olyvian|Park Place|PrideCo|Quick Real|Residential Capital|Revere|RWC|SCRED|SLA Capital|Stratton|TBG Capital|Titan Capital/)?'Web + LinkedIn research':'Highland Opportunities Google Drive'}));

