'use client';
import {useState} from 'react';
import {lenders,type Lender} from './lenders';
type Tab='home'|'directory'|'submission';
type Deal={transaction:'Purchase'|'Refinance';property:string;purpose:string;state:string;address:string;purchase:number;payoff:number;paidToDate:number;asis:number;budget:number;arv:number;fico:number;liquidity:number;experience:number};
const money=(n:number)=>n?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n):'$0';
export default function Home(){
 const[tab,setTab]=useState<Tab>('home'); const[selected,setSelected]=useState<Lender[]>([]);
 const[deal,setDeal]=useState<Deal>({transaction:'Purchase',property:'Single Family',purpose:'Construction',state:'WA',address:'Vancouver, WA',purchase:650000,payoff:520000,paidToDate:725000,asis:725000,budget:900000,arv:2200000,fico:700,liquidity:350000,experience:4});
 const update=(key:keyof Deal,value:string|number)=>setDeal(d=>({...d,[key]:value}));
 const simpleLoan=deal.purpose==='DSCR'||deal.purpose==='Bridge';
 const effectiveBudget=simpleLoan?0:deal.budget;
 const requestBasis=deal.transaction==='Purchase'?deal.purchase:deal.payoff;
 const costBasis=deal.transaction==='Purchase'?deal.purchase:deal.paidToDate;
 const request=requestBasis+effectiveBudget;
 const totalCost=costBasis+effectiveBudget;
 const ltc=totalCost?request/totalCost*100:0;
 const ltv=deal.asis?request/deal.asis*100:0;
 const ltarv=deal.arv?request/deal.arv*100:0;
 const choose=(l:Lender)=>setSelected(s=>s.some(x=>x.name===l.name)?s.filter(x=>x.name!==l.name):[...s,l]);
 return <main><header className="topbar"><button className="brand" onClick={()=>setTab('home')}><span className="mark">HO</span><span><b>Highland Opportunities</b><small>CAPITAL SOURCES</small></span></button><nav>{[['home','Home'],['directory','Capital Groups'],['submission','Submission Builder']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id as Tab)}>{label}</button>)}</nav><button className="shortlist" onClick={()=>setTab('submission')}>Selected <span>{selected.length}</span></button></header>
 {tab==='home'&&<><section className="hero"><div><p className="eyebrow">REAL ESTATE CAPITAL INTAKE</p><h1>Structure the request.<br/><em>See the leverage clearly.</em></h1><p className="lede">Build a complete financing request with the project basis, budget, value and sponsor facts in one place.</p></div><div className="hero-stat"><b>{lenders.length}</b><span>capital sources cataloged</span><small>No lender recommendations are generated on this page.</small></div></section><section className="workspace no-recs"><div className="intake"><div className="section-head"><span>01</span><div><h2>Deal profile</h2><p>Loan request equals purchase basis or refinance costs paid to date, plus the project budget.</p></div></div><div className="grid">
 <label>Transaction<select value={deal.transaction} onChange={e=>update('transaction',e.target.value)}><option>Purchase</option><option>Refinance</option></select></label>
 <label>Property type<select value={deal.property} onChange={e=>update('property',e.target.value)}><option>Single Family</option><option>2–4 Unit</option><option>Multifamily 5+</option><option>Commercial</option><option>Mixed Use</option><option>Industrial</option><option>Hospitality</option><option>Land</option><option>Mobile Home Park</option><option>Self Storage</option><option>Senior Housing</option></select></label>
 <label>Project / loan purpose<select value={deal.purpose} onChange={e=>update('purpose',e.target.value)}><option>Construction</option><option>AD&C / Land Development</option><option>Fix & Flip</option><option>DSCR</option><option>Bridge</option><option>Commercial</option><option>Multifamily</option><option>Build-to-Rent</option><option>Land</option></select></label>
 <label>State<select value={deal.state} onChange={e=>update('state',e.target.value)}>{['WA','OR','CA','AZ','TX','FL','CO','UT','ID','NV','Other'].map(x=><option key={x}>{x}</option>)}</select></label>
 <label className="wide">Property address / location<input value={deal.address} onChange={e=>update('address',e.target.value)}/></label>
 {deal.transaction==='Purchase'?<label>Purchase price<input type="number" value={deal.purchase} onChange={e=>update('purchase',+e.target.value)}/></label>:<><label>Current loan payoff<input type="number" value={deal.payoff} onChange={e=>update('payoff',+e.target.value)}/></label><label>Costs paid to date<input type="number" value={deal.paidToDate} onChange={e=>update('paidToDate',+e.target.value)}/></label></>}
 <label>As-is value<input type="number" value={deal.asis} onChange={e=>update('asis',+e.target.value)}/></label>{!simpleLoan&&<><label>Project budget total<input type="number" value={deal.budget} onChange={e=>update('budget',+e.target.value)}/></label><label>ARV / stabilized value<input type="number" value={deal.arv} onChange={e=>update('arv',+e.target.value)}/></label></>}
 </div><div className="section-head sponsor"><span>02</span><div><h2>Sponsor strength</h2><p>Indicative information only—no credit pull.</p></div></div><div className="grid"><label>Estimated FICO<input type="number" min="300" max="850" value={deal.fico} onChange={e=>update('fico',+e.target.value)}/></label><label>Verified liquidity<input type="number" value={deal.liquidity} onChange={e=>update('liquidity',+e.target.value)}/></label><label>Similar projects in past 4 years<input type="number" value={deal.experience} onChange={e=>update('experience',+e.target.value)}/></label></div></div>
 <aside className="results summary-panel"><p className="eyebrow">AUTOMATIC LOAN REQUEST</p><h2>{money(request)}</h2><p className={`formula ${simpleLoan?'single-basis':''}`}>{deal.transaction==='Purchase'?'Purchase price':'Current loan payoff'} <b>{money(requestBasis)}</b>{!simpleLoan&&<><span>+</span>Project budget <b>{money(effectiveBudget)}</b></>}</p><div className="exclusion">Closing costs and interest reserve are not included.</div><div className={`ratio-grid ${simpleLoan?'simple':''}`}><div><small>LOAN TO COST</small><b>{ltc.toFixed(1)}%</b><span>{money(request)} ÷ {money(totalCost)} total cost basis</span></div><div><small>LOAN TO VALUE</small><b>{ltv.toFixed(1)}%</b><span>{money(request)} ÷ {money(deal.asis)} as-is value</span></div>{!simpleLoan&&<div><small>LOAN TO ARV</small><b>{ltarv.toFixed(1)}%</b><span>{money(request)} ÷ {money(deal.arv)} ARV / stabilized value</span></div>}</div><dl><div><dt>As-is value</dt><dd>{money(deal.asis)}</dd></div><div><dt>Total cost basis</dt><dd>{money(totalCost)}</dd></div><div><dt>Current payoff</dt><dd>{deal.transaction==='Refinance'?money(deal.payoff):'Not applicable'}</dd></div><div><dt>Transaction</dt><dd>{deal.transaction}</dd></div><div><dt>Purpose</dt><dd>{deal.purpose}</dd></div></dl><button className="primary" onClick={()=>setTab('submission')}>Build submission summary</button></aside></section></>}
 {tab==='directory'&&<Directory selected={selected} choose={choose}/>} {tab==='submission'&&<Submission deal={deal} request={request} totalCost={totalCost} ltc={ltc} ltv={ltv} ltarv={ltarv} selected={selected}/>}</main>
}
function Directory({selected,choose}:{selected:Lender[];choose:(l:Lender)=>void}){const[q,setQ]=useState('');const[type,setType]=useState('All');const[url,setUrl]=useState('');const types=['All',...Array.from(new Set(lenders.map(l=>l.type))).sort()];const list=lenders.filter(l=>(type==='All'||l.type===type)&&(l.name+l.type+l.products.join(' ')+l.states).toLowerCase().includes(q.toLowerCase()));return <section className="page"><div className="page-title"><p className="eyebrow">CAPITAL INTELLIGENCE</p><h1>Capital group directory</h1><p>A consolidated directory—not a recommendation list—from Highland Opportunities spreadsheets, official websites and LinkedIn research. Program details must be reconfirmed.</p></div><div className="type-guide"><div><b>Direct / balance-sheet lender</b><span>Uses its own or controlled capital.</span></div><div><b>Institutional lender / debt fund</b><span>Scaled credit with repeatable programs.</span></div><div><b>Family office</b><span>Private wealth offering bespoke debt or equity.</span></div><div><b>Hard money lender</b><span>Asset-based, short-duration capital.</span></div><div><b>Insurance / permanent capital</b><span>Long-duration financing for stabilized assets.</span></div><div><b>Broker / capital advisor</b><span>Places a deal with third-party capital.</span></div></div><div className="add-lender"><div><b>Add a lender for research</b><p>Paste a company URL to queue it for verification.</p></div><input placeholder="https://lender.com" value={url} onChange={e=>setUrl(e.target.value)}/><button onClick={()=>{if(url){alert('URL captured for the next research pass.');setUrl('')}}}>Add URL</button></div><div className="directory-tools"><input placeholder="Search company, product, type or state…" value={q} onChange={e=>setQ(e.target.value)}/><select value={type} onChange={e=>setType(e.target.value)}>{types.map(x=><option key={x}>{x}</option>)}</select><span>{list.length} groups</span></div><div className="table-wrap"><table><thead><tr><th>Capital group</th><th>Type</th><th>Products</th><th>Geography</th><th>Contact</th><th>Sources</th><th></th></tr></thead><tbody>{list.map(l=><tr key={l.name}><td className="company-cell"><b>{l.name}</b></td><td>{l.type}</td><td><div className="chips">{l.products.slice(0,4).map(x=><span key={x}>{x}</span>)}</div></td><td>{l.states}</td><td className="contact-cell"><b>{l.contact||'Contact not listed'}</b>{l.email?<a href={`mailto:${l.email}`}>{l.email}</a>:<span>—</span>}<small>{l.phone||'Phone not listed'}</small></td><td>{l.web&&<a href={l.web} target="_blank">Website</a>} {l.linkedin&&<> · <a href={l.linkedin} target="_blank">LinkedIn</a></>}<small>{l.source}</small></td><td><button className={selected.some(x=>x.name===l.name)?'chosen':''} onClick={()=>choose(l)}>{selected.some(x=>x.name===l.name)?'Selected':'Select'}</button></td></tr>)}</tbody></table></div></section>}
function Submission({deal,request,totalCost,ltc,ltv,ltarv,selected}:{deal:Deal;request:number;totalCost:number;ltc:number;ltv:number;ltarv:number;selected:Lender[]}){const requestBasis=deal.transaction==='Purchase'?deal.purchase:deal.payoff;const simpleLoan=deal.purpose==='DSCR'||deal.purpose==='Bridge';const projectLines=simpleLoan?'':`\nProject budget: ${money(deal.budget)}\nARV / stabilized value: ${money(deal.arv)}\nLoan-to-ARV: ${ltarv.toFixed(1)}%`;const calculation=simpleLoan?`${money(requestBasis)} ${deal.transaction==='Purchase'?'purchase price':'current payoff'}`:`${money(requestBasis)} ${deal.transaction==='Purchase'?'purchase price':'current payoff'} + ${money(deal.budget)} budget`;const text=`Subject: ${deal.address} — ${deal.purpose} financing request\n\nHighland Opportunities requests an initial review of the following opportunity.\n\nPROPERTY\nAddress: ${deal.address}\nProperty type: ${deal.property}\nTransaction: ${deal.transaction}\nPurpose: ${deal.purpose}\n${deal.transaction==='Purchase'?`Purchase price: ${money(deal.purchase)}`:`Current payoff: ${money(deal.payoff)}\nCosts paid to date: ${money(deal.paidToDate)}`}\nTotal cost basis: ${money(totalCost)}\nTotal loan request: ${money(request)}\nAs-is value: ${money(deal.asis)}${projectLines}\nLoan-to-cost: ${ltc.toFixed(1)}%\nLoan-to-value (as-is): ${ltv.toFixed(1)}%\n\nLoan request calculation: ${calculation}. Closing costs and interest reserve are excluded.\n\nSPONSOR\nEstimated FICO: ${deal.fico}\nVerified liquidity: ${money(deal.liquidity)}\nSimilar completed projects (past 4 years): ${deal.experience}\n\nPlease confirm preliminary fit, leverage, rate, points, term, recourse, reserves, draw process, appraisal requirements and closing timeline.`;return <section className="page submission"><div className="page-title"><p className="eyebrow">DEAL DESK</p><h1>Submission builder</h1><p>One copy-ready summary generated from the intake.</p></div><div className="submission-grid"><div><h2>Selected recipients</h2>{selected.length?selected.map(l=><article className="recipient" key={l.name}><b>{l.name}</b><span>{l.contact}</span><a href={`mailto:${l.email}`}>{l.email||'Use website intake'}</a></article>):<div className="empty">Select capital groups from the directory if you want a recipient list.</div>}</div><div className="copy-card"><div><h2>Copy-ready submission</h2><button onClick={()=>navigator.clipboard.writeText(text)}>Copy to clipboard</button></div><pre>{text}</pre></div></div></section>}

